import { MenuGroupType } from "./types";


export const menu: MenuGroupType[] = [
    {   
        "name": "encode",
        "links": [
            {"name": "URL Encode", "link": "/encoding/url-encode", "type": "web", "tag": "popular"},
            {"name": "URL Decode", "link": "/encoding/url-decode", "type": "web", "tag": "popular"},
            {"name": "Unicode URL Encode", "link": "/encoding/unicode-url-encode", "type": "web", "tag": ""},
            {"name": "HTML Encode", "link": "/encoding/html-encode", "type": "web", "tag": ""},
            {"name": "HTML Decode", "link": "/encoding/html-decode", "type": "web", "tag": "popular"},
            {"name": "Base64 Encode", "link": "/encoding/base64-encode", "type": "web", "tag": "popular"},
            {"name": "Base64 Decode", "link": "/encoding/base64-decode", "type": "web", "tag": "popular"},
            {"name": "Base32 Encode", "link": "/encoding/base32-encode", "type": "web", "tag": ""},
            {"name": "Base32 Decode", "link": "/encoding/base32-decode", "type": "web", "tag": ""},
            {"name": "Base58 Encode", "link": "/encoding/base58-encode", "type": "web", "tag": ""},
            {"name": "Base58 Decode", "link": "/encoding/base58-decode", "type": "web", "tag": ""},
            {"name": "Ascii85 Encode", "link": "/encoding/ascii85-encode", "type": "web", "tag": ""},
            {"name": "Ascii85 Decode", "link": "/encoding/ascii85-decode", "type": "web", "tag": ""},
            {"name": "ROT13", "link": "/encoding/rot13", "type": "cipher", "tag": ""},
            {"name": "ROT47", "link": "/encoding/rot47", "type": "cipher", "tag": ""},
            {"name": "Caesar Cipher", "link": "/encoding/caesar-cipher", "type": "cipher", "tag": ""},
            {"name": "Morse Code Encode", "link": "/encoding/morse-encode", "type": "cipher", "tag": ""},
            {"name": "Morse Code Decode", "link": "/encoding/morse-decode", "type": "cipher", "tag": ""},
            {"name": "Morse Code Converter", "link": "/encoding/morse-code", "type": "cipher", "tag": ""},
            {"name": "Punycode Encode", "link": "/encoding/punycode-encode", "type": "web", "tag": ""},
            {"name": "Punycode Decode", "link": "/encoding/punycode-decode", "type": "web", "tag": ""},
            {"name": "Quoted-Printable Encode", "link": "/encoding/quoted-printable-encode", "type": "web", "tag": ""},
            {"name": "Quoted-Printable Decode", "link": "/encoding/quoted-printable-decode", "type": "web", "tag": ""},
            {"name": "Quoted-Printable", "link": "/encoding/quoted-printable", "type": "encoding", "tag": ""},
            {"name": "Base64URL Encode", "link": "/encoding/base64url-encode", "type": "web", "tag": ""},
            {"name": "Base64URL Decode", "link": "/encoding/base64url-decode", "type": "web", "tag": ""},
            {"name": "Base32", "link": "/encoding/base32", "type": "encoding", "tag": ""},
            {"name": "PEM Viewer", "link": "/encoding/pem-viewer", "type": "encoding", "tag": ""},
            {"name": "Hex Viewer", "link": "/encoding/hex-viewer", "type": "encoding", "tag": ""},
            {"name": "SSH Key Info", "link": "/encoding/ssh-key", "type": "encoding", "tag": ""},
            {"name": "Unicode Lookup", "link": "/encoding/unicode", "type": "encoding", "tag": ""},
            {"name": "Binary Visual", "link": "/encoding/binary-visual", "type": "encoding", "tag": ""},
            {"name": "JWK Inspector", "link": "/encoding/jwk", "type": "encoding", "tag": ""},
            {"name": "XOR Cipher", "link": "/encoding/xor-cipher", "type": "encoding", "tag": ""},
            {"name": "Affine Cipher", "link": "/encoding/affine-cipher", "type": "encoding", "tag": ""},
            {"name": "Rail Fence Cipher", "link": "/encoding/rail-fence", "type": "encoding", "tag": ""},
            {"name": "Bacon's Cipher", "link": "/encoding/bacon-cipher", "type": "cipher", "tag": ""},
            {"name": "Polybius Square", "link": "/encoding/polybius", "type": "cipher", "tag": ""},
            {"name": "Atbash Cipher", "link": "/encoding/atbash", "type": "cipher", "tag": ""},
            {"name": "Columnar Transposition", "link": "/encoding/columnar-transposition", "type": "cipher", "tag": ""},
            {"name": "Vigenère Cipher", "link": "/encoding/vigenere", "type": "cipher", "tag": ""},
            {"name": "Beaufort Cipher", "link": "/encoding/beaufort", "type": "cipher", "tag": ""},
            {"name": "Playfair Cipher", "link": "/encoding/playfair", "type": "cipher", "tag": ""},
            {"name": "Tap Code", "link": "/encoding/tap-code", "type": "cipher", "tag": ""},
            {"name": "Four-Square Cipher", "link": "/encoding/four-square", "type": "cipher", "tag": ""},
            {"name": "One-Time Pad", "link": "/encoding/otp", "type": "encoding", "tag": ""},
            {"name": "JWT Editor", "link": "/encoding/jwt-editor", "type": "encoding", "tag": ""},
            {"name": "Cert Chain Analyzer", "link": "/encoding/cert-chain", "type": "encoding", "tag": ""},
            {"name": "Base85 / Ascii85", "link": "/encoding/base85", "type": "encoding", "tag": ""},
            {"name": "Base62 Encode", "link": "/encoding/base62-encode", "type": "encoding", "tag": ""},
            {"name": "Base62 Decode", "link": "/encoding/base62-decode", "type": "encoding", "tag": ""},
        ],
       "color": "yellow",
        "titleColor": "yellowTitle",
        "typeColor": "yellowType" },
    {   
        "name": "hash",
        "links": [
            {"name": "MD5", "link": "/hashing/md5", "type": "web", "tag": "popular"},
            {"name": "SHA1", "link": "/hashing/sha1", "type": "web", "tag": ""},
            {"name": "SHA224", "link": "/hashing/sha224", "type": "web", "tag": ""},
            {"name": "SHA256", "link": "/hashing/sha256", "type": "web", "tag": "popular"},
            {"name": "SHA384", "link": "/hashing/sha384", "type": "web", "tag": ""},
            {"name": "SHA512", "link": "/hashing/sha512", "type": "web", "tag": ""},
            {"name": "SHA3-224", "link": "/hashing/sha3-224", "type": "web", "tag": ""},
            {"name": "SHA3-256", "link": "/hashing/sha3-256", "type": "web", "tag": ""},
            {"name": "SHA3-384", "link": "/hashing/sha3-384", "type": "web", "tag": ""},
            {"name": "SHA3-512", "link": "/hashing/sha3-512", "type": "web", "tag": ""},
            {"name": "Keccak-224", "link": "/hashing/keccak224", "type": "web3", "tag": ""},
            {"name": "Keccak-256", "link": "/hashing/keccak256", "type": "web3", "tag": ""},
            {"name": "Keccak-384", "link": "/hashing/keccak384", "type": "web3", "tag": ""},
            {"name": "Keccak-512", "link": "/hashing/keccak512", "type": "web3", "tag": ""},
            {"name": "RIPEMD160", "link": "/hashing/ripemd160", "type": "web3", "tag": ""},
            {"name": "HMAC-MD5", "link": "/hashing/hmac-md5", "type": "web", "tag": ""},
            {"name": "HMAC-SHA1", "link": "/hashing/hmac-sha1", "type": "web", "tag": ""},
            {"name": "HMAC-SHA224", "link": "/hashing/hmac-sha224", "type": "web", "tag": ""},
            {"name": "HMAC-SHA256", "link": "/hashing/hmac-sha256", "type": "web", "tag": "popular"},
            {"name": "HMAC-SHA384", "link": "/hashing/hmac-sha384", "type": "web", "tag": ""},
            {"name": "HMAC-SHA512", "link": "/hashing/hmac-sha512", "type": "web", "tag": ""},
            {"name": "HMAC-SHA3", "link": "/hashing/hmac-sha3", "type": "web", "tag": ""},
            {"name": "HMAC-RIPEMD160", "link": "/hashing/hmac-ripemd160", "type": "web3", "tag": ""},
            {"name": "CRC32", "link": "/hashing/crc32", "type": "web", "tag": ""},
            {"name": "HMAC Generator", "link": "/hashing/hmac-generator", "type": "hashing", "tag": ""},
            {"name": "Bcrypt Info", "link": "/hashing/bcrypt-info", "type": "hashing", "tag": ""},
            {"name": "Fletcher Checksum", "link": "/hashing/fletcher", "type": "hashing", "tag": ""},
            {"name": "MurmurHash", "link": "/hashing/murmur", "type": "hashing", "tag": ""},
            {"name": "FNV Hash", "link": "/hashing/fnv", "type": "hashing", "tag": ""},
            {"name": "NTLM Hash", "link": "/hashing/ntlm", "type": "hashing", "tag": ""},
        ],
       "color": "teal",
        "titleColor": "tealTitle",
        "typeColor": "tealType" },
        {
            "name": "convert",
            "links": [
                {"name": "Text Replace", "link": "/converting/text-replace", "type": "text", "tag": ""},
                {"name": "String to Binary", "link": "/converting/string-to-binary", "type": "binary", "tag": ""},
                {"name": "Binary to String", "link": "/converting/binary-to-string", "type": "binary", "tag": ""},
                {"name": "Binary to Hex", "link": "/converting/binary-to-hex", "type": "binary", "tag": ""},
                {"name": "Hex to Binary", "link": "/converting/hex-to-binary", "type": "binary", "tag": ""},
                {"name": "Text to Hex", "link": "/converting/text-to-hex", "type": "binary", "tag": ""},
                {"name": "Hex to Text", "link": "/converting/hex-to-text", "type": "binary", "tag": ""},
                {"name": "Dec to Hex", "link": "/converting/dec-to-hex", "type": "binary", "tag": ""},
                {"name": "Hex to Dec", "link": "/converting/hex-to-dec", "type": "binary", "tag": ""},
                {"name": "Dec to Octal", "link": "/converting/dec-to-octal", "type": "binary", "tag": ""},
                {"name": "Octal to Dec", "link": "/converting/octal-to-dec", "type": "binary", "tag": ""},
                {"name": "Unix Timestamp Converter", "link": "/converting/unix-timestamp", "type": "date", "tag": "popular"},
                {"name": "String to Bytes32", "link": "/converting/string-to-bytes32", "type": "web3", "tag": "popular"},
                {"name": "Bytes32 to String", "link": "/converting/bytes32-to-string", "type": "web3", "tag": "popular"},
                {"name": "Number to Bytes32", "link": "/converting/number-to-bytes32", "type": "web3", "tag": "popular"},
                {"name": "Bytes32 to Number", "link": "/converting/bytes32-to-number", "type": "web3", "tag": "popular"},
                {"name": "Ethereum Public Key To Address", "link": "/converting/eth-public-to-address", "type": "web3", "tag": ""},
                {"name": "Hex To RGB", "link": "/converting/hex-to-rgb", "type": "UX", "tag": ""},
                {"name": "RGB To Hex", "link": "/converting/rgb-to-hex", "type": "UX", "tag": ""},
                {"name": "RGB To CMYK", "link": "/converting/rgb-to-cmyk", "type": "UX", "tag": ""},
                {"name": "CMYK To RGB", "link": "/converting/cmyk-to-rgb", "type": "UX", "tag": ""},
                {"name": "JSON to YAML", "link": "/converting/json-to-yaml", "type": "data", "tag": ""},
                {"name": "YAML to JSON", "link": "/converting/yaml-to-json", "type": "data", "tag": ""},
                {"name": "JSON to XML", "link": "/converting/json-to-xml", "type": "data", "tag": ""},
                {"name": "XML to JSON", "link": "/converting/xml-to-json", "type": "data", "tag": ""},
                {"name": "JSON to CSV", "link": "/converting/json-to-csv", "type": "data", "tag": ""},
                {"name": "CSV to JSON", "link": "/converting/csv-to-json", "type": "data", "tag": ""},
                {"name": "JSON to TOML", "link": "/converting/json-to-toml", "type": "data", "tag": ""},
                {"name": "TOML to JSON", "link": "/converting/toml-to-json", "type": "data", "tag": ""},
                {"name": "CSV to XML", "link": "/converting/csv-to-xml", "type": "data", "tag": ""},
                {"name": "XML to CSV", "link": "/converting/xml-to-csv", "type": "data", "tag": ""},
                {"name": "CSV to Markdown Table", "link": "/converting/csv-to-markdown-table", "type": "data", "tag": ""},
                {"name": "Markdown Table to CSV", "link": "/converting/markdown-table-to-csv", "type": "data", "tag": ""},
                {"name": "HTML Table to CSV", "link": "/converting/html-table-to-csv", "type": "data", "tag": ""},
                {"name": "HTML Table to JSON", "link": "/converting/html-table-to-json", "type": "data", "tag": ""},
                {"name": "JSON to TypeScript", "link": "/converting/json-to-typescript", "type": "data", "tag": ""},
                {"name": "JSON to Go Struct", "link": "/converting/json-to-go-struct", "type": "data", "tag": ""},
                {"name": "JSON to Rust Struct", "link": "/converting/json-to-rust-struct", "type": "data", "tag": ""},
                {"name": "JSON to Zod Schema", "link": "/converting/json-to-zod", "type": "data", "tag": ""},
                {"name": "Markdown to HTML", "link": "/converting/markdown-to-html", "type": "data", "tag": ""},
                {"name": "Markdown to HTML (v2)", "link": "/converting/markdown-html", "type": "data", "tag": ""},
                {"name": "HTML to Markdown", "link": "/converting/html-to-markdown", "type": "data", "tag": ""},
                {"name": "HTML to JSX", "link": "/converting/html-to-jsx", "type": "data", "tag": ""},
                {"name": "Date Format Converter", "link": "/converting/date-format-converter", "type": "date", "tag": ""},
                {"name": "Time Zone Converter", "link": "/converting/time-zone-converter", "type": "date", "tag": ""},
                {"name": "Cron to Human Readable", "link": "/converting/cron-to-human", "type": "date", "tag": ""},
                {"name": "Week Number Calculator", "link": "/converting/week-number-calculator", "type": "date", "tag": ""},
                {"name": "Binary to Decimal", "link": "/converting/binary-to-decimal", "type": "number", "tag": ""},
                {"name": "Decimal to Binary", "link": "/converting/decimal-to-binary", "type": "number", "tag": ""},
                {"name": "Roman to Arabic", "link": "/converting/roman-to-arabic", "type": "number", "tag": ""},
                {"name": "Arabic to Roman", "link": "/converting/arabic-to-roman", "type": "number", "tag": ""},
                {"name": "Roman Numeral Converter", "link": "/converting/roman-numerals", "type": "number", "tag": ""},
                {"name": "Number to Words", "link": "/converting/number-to-words", "type": "number", "tag": ""},
                {"name": "Number to Words (Ordinal)", "link": "/converting/number-words", "type": "number", "tag": ""},
                {"name": "Length Converter", "link": "/converting/length-converter", "type": "unit", "tag": ""},
                {"name": "Weight Converter", "link": "/converting/weight-converter", "type": "unit", "tag": ""},
                {"name": "Temperature Converter", "link": "/converting/temperature-converter", "type": "unit", "tag": ""},
                {"name": "Area Converter", "link": "/converting/area-converter", "type": "unit", "tag": ""},
                {"name": "Angle Converter", "link": "/converting/angle-converter", "type": "unit", "tag": ""},
                {"name": "Bitrate Converter", "link": "/converting/bitrate-converter", "type": "unit", "tag": ""},
                {"name": "HEX to HSL", "link": "/converting/hex-to-hsl", "type": "UX", "tag": ""},
                {"name": "HSL to HEX", "link": "/converting/hsl-to-hex", "type": "UX", "tag": ""},
                {"name": "RGB to HSL", "link": "/converting/rgb-to-hsl", "type": "UX", "tag": ""},
                {"name": "HSL to RGB", "link": "/converting/hsl-to-rgb", "type": "UX", "tag": ""},
                {"name": "HEX to HSV", "link": "/converting/hex-to-hsv", "type": "UX", "tag": ""},
                {"name": "HSV to HEX", "link": "/converting/hsv-to-hex", "type": "UX", "tag": ""},
                {"name": "Color Name to HEX", "link": "/converting/color-name-to-hex", "type": "UX", "tag": ""},
                {"name": "HEX to Color Name", "link": "/converting/hex-to-color-name", "type": "UX", "tag": ""},
                {"name": "Gradient Generator", "link": "/converting/gradient-generator", "type": "UX", "tag": ""},
                {"name": "Color Palette Extractor", "link": "/converting/color-palette-extractor", "type": "UX", "tag": ""},
                {"name": "YAML to TOML", "link": "/converting/yaml-to-toml", "type": "data", "tag": ""},
                {"name": "TOML to YAML", "link": "/converting/toml-to-yaml", "type": "data", "tag": ""},
                {"name": "INI to JSON", "link": "/converting/ini-to-json", "type": "data", "tag": ""},
                {"name": "JSON to INI", "link": "/converting/json-to-ini", "type": "data", "tag": ""},
                {"name": "Number Base Converter", "link": "/converting/number-base-converter", "type": "binary", "tag": ""},
                {"name": "Base Converter Extended", "link": "/converting/base-convert", "type": "binary", "tag": ""},
                {"name": "JSON Flattener", "link": "/converting/json-flatten", "type": "data", "tag": ""},
                {"name": "Hex Dump", "link": "/converting/hex-dump", "type": "binary", "tag": ""},
                {"name": "Unicode Escape", "link": "/converting/unicode-escape", "type": "text", "tag": ""},
                {"name": "JSON Escape", "link": "/converting/json-escape", "type": "text", "tag": ""},
                {"name": "JSON Unescape", "link": "/converting/json-unescape", "type": "text", "tag": ""},
                {"name": "Number Formatter", "link": "/converting/number-format", "type": "text", "tag": ""},
                {"name": "SVG to Data URI", "link": "/converting/svg-to-data-uri", "type": "UX", "tag": ""},
                {"name": "CSS Unit Converter", "link": "/converting/css-units", "type": "UX", "tag": ""},
                {"name": "JSON to SQL", "link": "/converting/json-to-sql", "type": "data", "tag": ""},
                {"name": "Markdown Table", "link": "/converting/markdown-table", "type": "data", "tag": ""},
                {"name": "JSON Diff", "link": "/converting/json-diff", "type": "data", "tag": ""},
                {"name": "JSON to PHP", "link": "/converting/json-to-php", "type": "data", "tag": ""},
                {"name": "JSON to Java", "link": "/converting/json-to-java", "type": "data", "tag": ""},
                {"name": "Px to Rem", "link": "/converting/px-rem", "type": "UX", "tag": ""},
                {"name": "Color Mixer", "link": "/converting/color-mixer", "type": "UX", "tag": ""},
                {"name": "SVG Cleaner", "link": "/converting/svg-cleaner", "type": "UX", "tag": ""},
                {"name": ".env Parser", "link": "/converting/env-parser", "type": "data", "tag": ""},
                {"name": "JSON Minifier", "link": "/converting/json-minify", "type": "data", "tag": ""},
                {"name": "TOML Validator", "link": "/converting/toml-validator", "type": "data", "tag": ""},
                {"name": "Number Format", "link": "/converting/number-format-advanced", "type": "binary", "tag": ""},
                {"name": "CSS Variables", "link": "/converting/css-variables", "type": "UX", "tag": ""},
                {"name": "Git Config Parser", "link": "/converting/git-config", "type": "data", "tag": ""},
                {"name": "TS to JS", "link": "/converting/ts-to-js", "type": "data", "tag": ""},
                {"name": "Properties Parser", "link": "/converting/properties-parser", "type": "data", "tag": ""},
                {"name": "UUID to Timestamp", "link": "/converting/uuid-to-timestamp", "type": "dev", "tag": ""},
                {"name": "XML Validator", "link": "/converting/xml-validator", "type": "data", "tag": ""},
                {"name": "JSONL Parser", "link": "/converting/jsonl", "type": "data", "tag": ""},
                {"name": "Roman Calculator", "link": "/converting/roman-calculator", "type": "number", "tag": ""},
                {"name": "Color Temperature", "link": "/converting/color-temperature", "type": "UX", "tag": ""},
                {"name": "JSON Stats", "link": "/converting/json-stats", "type": "data", "tag": ""},
                {"name": "JSON Merge", "link": "/converting/json-merge", "type": "data", "tag": ""},
                {"name": "Tailwind Color Finder", "link": "/converting/tailwind-colors", "type": "UX", "tag": ""},
                {"name": "Tailwind Shades", "link": "/converting/tailwind-shades", "type": "color", "tag": ""},
                {"name": "JSON to ASCII Table", "link": "/converting/json-table", "type": "data", "tag": ""},
                {"name": "Color Scheme Generator", "link": "/converting/color-scheme", "type": "UX", "tag": ""},
                {"name": "Text to HTML Table", "link": "/converting/text-to-html-table", "type": "data", "tag": ""},
                {"name": "Number to Color", "link": "/converting/number-to-color", "type": "UX", "tag": ""},
                {"name": "Scientific Notation", "link": "/converting/scientific-notation", "type": "number", "tag": ""},
                {"name": "Data URL Creator", "link": "/converting/data-url", "type": "binary", "tag": ""},
                {"name": "Color Contrast Checker", "link": "/converting/color-contrast", "type": "color", "tag": ""},
                {"name": "JSON Sorter", "link": "/converting/json-sort", "type": "data", "tag": ""},
                {"name": "Decimal to Fraction", "link": "/converting/decimal-fraction", "type": "number", "tag": ""},
                {"name": "Color Picker Helper", "link": "/converting/color-picker", "type": "color", "tag": ""},
                {"name": "CSS Gradient Generator", "link": "/converting/css-gradient", "type": "color", "tag": ""},
                {"name": "INI Parser", "link": "/converting/ini-parser", "type": "json", "tag": ""},
                {"name": "CSV / JSON Converter", "link": "/converting/csv-json", "type": "data", "tag": ""},
                {"name": "Numeral Systems", "link": "/converting/numeral-systems", "type": "number", "tag": ""},
                {"name": "Colorblind Simulator", "link": "/converting/colorblind", "type": "color", "tag": ""},
                {"name": "GraphQL to TypeScript", "link": "/converting/graphql-to-ts", "type": "json", "tag": ""},
                {"name": "CSV Statistics", "link": "/converting/csv-stats", "type": "json", "tag": ""},
                {"name": "Code Minifier", "link": "/converting/code-minifier", "type": "json", "tag": ""},
                {"name": "SI Prefix Converter", "link": "/converting/si-prefix", "type": "number", "tag": ""},
                {"name": "Julian Day Number", "link": "/converting/julian-day", "type": "number", "tag": ""},
                {"name": "JSON Schema Generator", "link": "/converting/json-schema", "type": "json", "tag": ""},
                {"name": "TypeScript to Zod", "link": "/converting/ts-to-zod", "type": "json", "tag": ""},
                {"name": "Protobuf Decoder", "link": "/converting/protobuf", "type": "json", "tag": ""},
                {"name": "Properties to JSON", "link": "/converting/properties-json", "type": "json", "tag": ""},
                {"name": "REST to GraphQL", "link": "/converting/rest-to-graphql", "type": "json", "tag": ""},
                {"name": "Python to JS Syntax", "link": "/converting/py-to-js", "type": "json", "tag": ""},
                {"name": "Fluid Typography", "link": "/converting/fluid-type", "type": "json", "tag": ""},
                {"name": "Box Shadow Generator", "link": "/converting/box-shadow", "type": "json", "tag": ""},
                {"name": "SVG Path Analyzer", "link": "/converting/svg-path", "type": "json", "tag": ""},
                {"name": "BPM / MS Converter", "link": "/converting/bpm", "type": "number", "tag": ""},
                {"name": "White Balance", "link": "/converting/white-balance", "type": "color", "tag": ""},
                {"name": "Type Scale Generator", "link": "/converting/type-scale", "type": "json", "tag": ""},
                {"name": "Endianness Converter", "link": "/converting/endianness", "type": "binary", "tag": ""},
                {"name": "Unit Converter", "link": "/converting/unit-converter", "type": "unit", "tag": ""}
            ],
           "color": "cyan",
            "titleColor": "cyanTitle",
            "typeColor": "cyanType" },
            {
                "name": "tools",
                "links": [
                    {"name": "Relative Luminance Calculator", "link": "/tools/relative-luminance", "type": "UX", "tag": ""},
                    {"name": "Screen Size Calculator", "link": "/tools/browser-size", "type": "UX", "tag": ""},
                    {"name": "Password Generator", "link": "/tools/password-generator", "type": "Security", "tag": "popular"},
                    {"name": "WiFi QR Code Generator", "link": "/tools/wifi-qr-generator", "type": "Security", "tag": ""},
                    {"name": "Nmap Viewer", "link": "/tools/nmap-viewer", "type": "Security", "tag": ""},
                    {"name": "Google Maps API Scanner", "link": "/tools/gmaps-api-scanner", "type": "Security", "tag": ""},
                    {"name": "Bcrypt Password Checker", "link": "/tools/bcrypt-checker", "type": "Security", "tag": ""},
                    {"name": "DES Encrypt", "link": "/tools/des-encrypt", "type": "Security", "tag": ""},
                    {"name": "DES Decrypt", "link": "/tools/des-decrypt", "type": "Security", "tag": ""},
                    {"name": "Triple DES Encrypt", "link": "/tools/triple-des-encrypt", "type": "Security", "tag": ""},
                    {"name": "Triple DES Decrypt", "link": "/tools/triple-des-decrypt", "type": "Security", "tag": ""},
                    {"name": "RC4 Encrypt", "link": "/tools/rc4-encrypt", "type": "Security", "tag": ""},
                    {"name": "RC4 Decrypt", "link": "/tools/rc4-decrypt", "type": "Security", "tag": ""},
                    {"name": "Rabbit Encrypt", "link": "/tools/rabbit-encrypt", "type": "Security", "tag": ""},
                    {"name": "Rabbit Decrypt", "link": "/tools/rabbit-decrypt", "type": "Security", "tag": ""},
                    {"name": "My IP Address", "link": "/tools/my-ip", "type": "dev", "tag": ""},
                    {"name": "JSON Formatter", "link": "/tools/json-formatter", "type": "code", "tag": "popular"},
                    {"name": "XML Formatter", "link": "/tools/xml-formatter", "type": "code", "tag": ""},
                    {"name": "SQL Formatter", "link": "/tools/sql-formatter", "type": "code", "tag": ""},
                    {"name": "HTML Formatter", "link": "/tools/html-formatter", "type": "code", "tag": ""},
                    {"name": "CSS Formatter", "link": "/tools/css-formatter", "type": "code", "tag": ""},
                    {"name": "JS Formatter", "link": "/tools/js-formatter", "type": "code", "tag": ""},
                    {"name": "YAML Validator", "link": "/tools/yaml-validator", "type": "code", "tag": ""},
                    {"name": "Regex Tester", "link": "/tools/regex-tester", "type": "code", "tag": ""},
                    {"name": "ReDoS Checker", "link": "/tools/redos-checker", "type": "code", "tag": ""},
                    {"name": "UUID Generator", "link": "/tools/uuid-generator", "type": "dev", "tag": "popular"},
                    {"name": "ULID Generator", "link": "/tools/ulid-generator", "type": "dev", "tag": ""},
                    {"name": "QR Code Generator", "link": "/tools/qr-code-generator", "type": "dev", "tag": ""},
                    {"name": "Barcode Generator", "link": "/tools/barcode-generator", "type": "dev", "tag": ""},
                    {"name": "Bcrypt Hash Generator", "link": "/tools/bcrypt-generator", "type": "Security", "tag": ""},
                    {"name": ".htpasswd Generator", "link": "/tools/htpasswd-generator", "type": "Security", "tag": ""},
                    {"name": "RSA Key Pair Generator", "link": "/tools/rsa-key-pair-generator", "type": "Security", "tag": ""},
                    {"name": "Bitwise Calculator", "link": "/tools/bitwise-calculator", "type": "binary", "tag": ""},
                    {"name": "chmod Calculator", "link": "/tools/chmod-calculator", "type": "Security", "tag": ""},
                    {"name": "Statistics Calculator", "link": "/tools/statistics-calculator", "type": "text", "tag": ""},
                    {"name": ".gitignore Generator", "link": "/tools/gitignore-generator", "type": "dev", "tag": ""},
                    {"name": "Password Strength", "link": "/tools/password-strength", "type": "Security", "tag": ""},
                    {"name": "cURL to Fetch", "link": "/tools/curl-to-fetch", "type": "dev", "tag": ""},
                    {"name": "Text Statistics", "link": "/tools/text-statistics", "type": "text", "tag": ""},
                    {"name": "AES Encrypt", "link": "/tools/aes-encrypt", "type": "Security", "tag": ""},
                    {"name": "AES Decrypt", "link": "/tools/aes-decrypt", "type": "Security", "tag": ""},
                    {"name": "TOTP Generator", "link": "/tools/totp-generator", "type": "Security", "tag": ""},
                    {"name": "Extract from Text", "link": "/tools/extract-from-text", "type": "text", "tag": ""},
                    {"name": "Fake Data Generator", "link": "/tools/fake-data", "type": "dev", "tag": ""},
                    {"name": "Color Shades", "link": "/tools/color-shades", "type": "UX", "tag": ""},
                    {"name": "CSS Specificity", "link": "/tools/css-specificity", "type": "UX", "tag": ""},
                    {"name": "Semver Comparator", "link": "/tools/semver", "type": "dev", "tag": ""},
                    {"name": "Box Shadow", "link": "/tools/box-shadow", "type": "UX", "tag": ""},
                    {"name": "Border Radius", "link": "/tools/border-radius", "type": "UX", "tag": ""},
                    {"name": "UUID Validator", "link": "/tools/uuid-validator", "type": "dev", "tag": ""},
                    {"name": "JSON Schema Validator", "link": "/tools/json-schema-validator", "type": "code", "tag": ""},
                    {"name": "CSS Animation", "link": "/tools/css-animation", "type": "UX", "tag": ""},
                    {"name": "JSON to Python", "link": "/tools/json-to-python", "type": "code", "tag": ""},
                    {"name": "OTP Secret Generator", "link": "/tools/otp-secret", "type": "Security", "tag": ""},
                    {"name": "Char Frequency", "link": "/tools/char-frequency", "type": "text", "tag": ""},
                    {"name": "Meta Tags Generator", "link": "/tools/meta-tags", "type": "UX", "tag": ""},
                    {"name": "Cron Builder", "link": "/tools/cron-builder", "type": "dev", "tag": ""},
                    {"name": "Encoding Inspector", "link": "/tools/encoding-inspector", "type": "text", "tag": ""},
                    {"name": "Badge Generator", "link": "/tools/badge-generator", "type": "UX", "tag": ""},
                    {"name": "Email Validator", "link": "/tools/email-validator", "type": "dev", "tag": ""},
                    {"name": "Base64 File", "link": "/tools/base64-file", "type": "dev", "tag": ""},
                    {"name": "JSON Lint", "link": "/tools/json-lint", "type": "code", "tag": ""},
                    {"name": "GraphQL Formatter", "link": "/tools/graphql-formatter", "type": "code", "tag": ""},
                    {"name": "Hash Verifier", "link": "/tools/hash-verify", "type": "Security", "tag": ""},
                    {"name": "WHOIS Parser", "link": "/tools/whois-parser", "type": "Security", "tag": ""},
                    {"name": "Credit Card Validator", "link": "/tools/credit-card", "type": "dev", "tag": ""},
                    {"name": "Brainfuck Interpreter", "link": "/tools/brainfuck", "type": "code", "tag": ""},
                    {"name": "Percentage Calculator", "link": "/tools/percentage", "type": "text", "tag": ""},
                    {"name": "Date Difference", "link": "/tools/date-diff", "type": "date", "tag": ""},
                    {"name": "ISBN Validator", "link": "/tools/isbn", "type": "dev", "tag": ""},
                    {"name": "Haversine Distance", "link": "/tools/haversine", "type": "dev", "tag": ""},
                    {"name": "Geohash Encoder/Decoder", "link": "/tools/geohash", "type": "dev", "tag": ""},
                    {"name": "GPS Coordinate Converter", "link": "/tools/gps-coords", "type": "dev", "tag": ""},
                    {"name": "Astronomical Calculator", "link": "/tools/astronomy", "type": "dev", "tag": ""},
                    {"name": "Phone Number Formatter", "link": "/tools/phone-formatter", "type": "dev", "tag": ""},
                    {"name": "Conventional Commits", "link": "/tools/conventional-commits", "type": "dev", "tag": ""},
                    {"name": "Soundex Code", "link": "/tools/soundex", "type": "text", "tag": ""},
                    {"name": "Math Evaluator", "link": "/tools/math-eval", "type": "text", "tag": ""},
                    {"name": "Fibonacci Generator", "link": "/tools/fibonacci", "type": "text", "tag": ""},
                    {"name": "Prime Checker", "link": "/tools/prime", "type": "text", "tag": ""},
                    {"name": "Prime Factorization", "link": "/tools/prime-factors", "type": "text", "tag": ""},
                    {"name": "GCD & LCM Calculator", "link": "/tools/gcd-lcm", "type": "text", "tag": ""},
                    {"name": "Extended Euclidean Algorithm", "link": "/tools/extended-gcd", "type": "text", "tag": ""},
                    {"name": "Fraction Calculator", "link": "/tools/fractions", "type": "text", "tag": ""},
                    {"name": "Permutation & Combination", "link": "/tools/permutations", "type": "text", "tag": ""},
                    {"name": "World Clock", "link": "/tools/world-clock", "type": "date", "tag": ""},
                    {"name": "Timer & Stopwatch", "link": "/tools/timer", "type": "date", "tag": ""},
                    {"name": "Pomodoro Timer", "link": "/tools/pomodoro", "type": "date", "tag": ""},
                    {"name": "UUID Bulk Generator", "link": "/tools/uuid-bulk", "type": "dev", "tag": ""},
                    {"name": "Bitfield Viewer", "link": "/tools/bitfield", "type": "binary", "tag": ""},
                    {"name": "Entropy Calculator", "link": "/tools/entropy", "type": "text", "tag": ""},
                    {"name": "Hamming Distance", "link": "/tools/hamming", "type": "text", "tag": ""},
                    {"name": "Cron Expression Parser", "link": "/tools/cron-parser", "type": "dev", "tag": ""},
                    {"name": "Random Data Generator", "link": "/tools/random-data", "type": "generator", "tag": ""},
                    {"name": "Descriptive Statistics", "link": "/tools/descriptive-stats", "type": "text", "tag": ""},
                    {"name": "UUID v5 Generator", "link": "/tools/uuid-v5", "type": "dev", "tag": ""},
                    {"name": "QR Data Analyzer", "link": "/tools/qr-data", "type": "text", "tag": ""},
                    {"name": "Docker Compose to Run", "link": "/tools/docker-compose", "type": "dev", "tag": ""},
                    {"name": "Loan Calculator", "link": "/tools/loan-calc", "type": "text", "tag": ""},
                    {"name": "Semver Bumper", "link": "/tools/semver-bumper", "type": "dev", "tag": ""},
                    {"name": "Number Sequences", "link": "/tools/number-sequence", "type": "text", "tag": ""},
                    {"name": "Taylor Series", "link": "/tools/taylor-series", "type": "text", "tag": ""},
                    {"name": "Boolean Simplifier", "link": "/tools/boolean-simplifier", "type": "text", "tag": ""},
                    {"name": "Bitwise Operations", "link": "/tools/bitwise", "type": "text", "tag": ""},
                    {"name": "Barcode Decoder", "link": "/tools/barcode", "type": "text", "tag": ""},
                    {"name": "Ohm's Law Calculator", "link": "/tools/ohms-law", "type": "text", "tag": ""},
                    {"name": "Resistor Color Code", "link": "/tools/resistor", "type": "text", "tag": ""},
                    {"name": "OpenAPI Snippet", "link": "/tools/openapi", "type": "dev", "tag": ""},
                    {"name": "Postman Collection Viewer", "link": "/tools/postman-viewer", "type": "dev", "tag": ""},
                    {"name": "Correlation Calculator", "link": "/tools/correlation", "type": "text", "tag": ""},
                    {"name": "Z-Score Calculator", "link": "/tools/z-score", "type": "text", "tag": ""},
                    {"name": "Confidence Interval", "link": "/tools/confidence-interval", "type": "text", "tag": ""},
                    {"name": "Data Sampler", "link": "/tools/data-sampler", "type": "generator", "tag": ""},
                    {"name": "Sample Size Calculator", "link": "/tools/sample-size", "type": "text", "tag": ""},
                    {"name": "Linear Regression", "link": "/tools/linear-regression", "type": "text", "tag": ""},
                    {"name": "Data Type Analyzer", "link": "/tools/data-type-analyzer", "type": "text", "tag": ""},
                    {"name": "Moving Average", "link": "/tools/moving-average", "type": "text", "tag": ""},
                    {"name": "Chi-Square Test", "link": "/tools/chi-square", "type": "text", "tag": ""},
                    {"name": "Continued Fractions", "link": "/tools/continued-fraction", "type": "text", "tag": ""},
                    {"name": "Chinese Calendar", "link": "/tools/chinese-calendar", "type": "date", "tag": ""},
                    {"name": "vCard Generator", "link": "/tools/vcard", "type": "generator", "tag": ""},
                    {"name": "iCal Generator", "link": "/tools/ical", "type": "generator", "tag": ""},
                    {"name": "Nginx Config Generator", "link": "/tools/nginx-config", "type": "dev", "tag": ""},
                    {"name": ".htaccess Generator", "link": "/tools/htaccess", "type": "dev", "tag": ""},
                    {"name": "K8s YAML Generator", "link": "/tools/k8s-yaml", "type": "dev", "tag": ""},
                    {"name": "K8s Resource Calculator", "link": "/tools/k8s-resources", "type": "dev", "tag": ""},
                    {"name": "systemd Service", "link": "/tools/systemd", "type": "dev", "tag": ""},
                    {"name": "Systemd Unit Generator", "link": "/tools/systemd-gen", "type": "dev", "tag": ""},
                    {"name": "Terraform Vars", "link": "/tools/terraform", "type": "dev", "tag": ""},
                    {"name": "Terraform Variable Generator", "link": "/tools/terraform-vars", "type": "dev", "tag": ""},
                    {"name": "CI/CD Pipeline Generator", "link": "/tools/cicd-gen", "type": "dev", "tag": ""},
                    {"name": "Template Literal", "link": "/tools/template-literal", "type": "dev", "tag": ""},
                    {"name": "Array Operations", "link": "/tools/array-ops", "type": "dev", "tag": ""},
                    {"name": "Compound Interest", "link": "/tools/compound-interest", "type": "text", "tag": ""},
                    {"name": "ROI Calculator", "link": "/tools/roi-calc", "type": "text", "tag": ""},
                    {"name": "Loan Amortization", "link": "/tools/loan-amortization", "type": "text", "tag": ""},
                    {"name": "VAT / Tax Calculator", "link": "/tools/tax-calc", "type": "text", "tag": ""},
                    {"name": "Unit Price Comparator", "link": "/tools/unit-price", "type": "text", "tag": ""},
                    {"name": "DCF Calculator", "link": "/tools/dcf-calc", "type": "text", "tag": ""},
                    {"name": "Geometry Calculator", "link": "/tools/geometry", "type": "text", "tag": ""},
                    {"name": "ARIA Labels", "link": "/tools/aria-labels", "type": "dev", "tag": ""},
                    {"name": "Sudoku Validator", "link": "/tools/sudoku", "type": "text", "tag": ""},
                    {"name": "Magic Square", "link": "/tools/magic-square", "type": "generator", "tag": ""},
                    {"name": "Cryptarithmetic", "link": "/tools/cryptarith", "type": "text", "tag": ""},
                    {"name": "Tic-Tac-Toe Analyzer", "link": "/tools/tic-tac-toe", "type": "text", "tag": ""},
                    {"name": "FEN Parser", "link": "/tools/fen-parser", "type": "text", "tag": ""},
                    {"name": "Rate Limiter Calc", "link": "/tools/rate-limiter", "type": "dev", "tag": ""},
                    {"name": "API Mock Generator", "link": "/tools/api-mock", "type": "dev", "tag": ""},
                    {"name": "Binary Arithmetic", "link": "/tools/binary-arith", "type": "text", "tag": ""},
                    {"name": "Float Analyzer", "link": "/tools/float-analyzer", "type": "text", "tag": ""},
                    {"name": "Number Theory", "link": "/tools/number-theory", "type": "text", "tag": ""},
                    {"name": "Sequence Recognizer", "link": "/tools/sequence-recognizer", "type": "text", "tag": ""},
                    {"name": "IAM Policy Analyzer", "link": "/tools/iam-policy", "type": "dev", "tag": ""},
                    {"name": "Unix File Permissions", "link": "/tools/unix-permissions", "type": "Security", "tag": ""},
                    {"name": "Matrix Calculator (Advanced)", "link": "/tools/matrix-calc", "type": "binary", "tag": ""},
                    {"name": "Equation Solver", "link": "/tools/equation-solver", "type": "text", "tag": ""},
                    {"name": "Aspect Ratio Calculator", "link": "/tools/aspect-ratio-calc", "type": "UX", "tag": ""},
                    {"name": "OpenAPI Schema Generator", "link": "/tools/openapi-schema", "type": "dev", "tag": ""},
                    {"name": "GraphQL Schema Builder", "link": "/tools/graphql-schema", "type": "dev", "tag": ""},
                    {"name": "Set-Cookie Header Builder", "link": "/tools/setcookie-builder", "type": "dev", "tag": ""},
                    {"name": "HTTP Security Headers Checker", "link": "/tools/http-security-check", "type": "Security", "tag": ""},
                    {"name": "Semver Range Checker", "link": "/tools/semver-range", "type": "dev", "tag": ""},
                    {"name": "Git Commit Linter", "link": "/tools/git-commit-lint", "type": "dev", "tag": ""},
                    {"name": "SQL Query Analyzer", "link": "/tools/sql-analyzer", "type": "code", "tag": ""},
                    {"name": "Docker Compose Generator", "link": "/tools/docker-compose-gen", "type": "dev", "tag": ""},
                    {"name": "Makefile Generator", "link": "/tools/makefile-gen", "type": "dev", "tag": ""},
                    {"name": "RSA Key Info Parser", "link": "/tools/rsa-key-info", "type": "Security", "tag": ""},
                    {"name": "JWT Public Key Recovery (sign2n)", "link": "/tools/jwt-public-key-recovery", "type": "Security", "tag": ""},
                    {"name": "Unicode Character Inspector", "link": "/tools/unicode-inspector", "type": "text", "tag": ""},
                    {"name": "Passphrase Strength Checker", "link": "/tools/passphrase-strength", "type": "Security", "tag": ""},
                    {"name": "Bit Pattern Viewer", "link": "/tools/bit-pattern", "type": "binary", "tag": ""},
                    {"name": "JSON Path Evaluator", "link": "/tools/json-path", "type": "code", "tag": ""},
                    {"name": "Protobuf Schema Builder", "link": "/tools/protobuf-schema", "type": "dev", "tag": ""},
                    {"name": "Diff Viewer", "link": "/tools/diff-viewer", "type": "dev", "tag": ""},
                    {"name": "Calendar Week Calculator", "link": "/tools/calendar-week", "type": "date", "tag": ""},
                    {"name": "Timezone Overlap Finder", "link": "/tools/timezone-overlap", "type": "date", "tag": ""},
                    {"name": "Changelog Generator", "link": "/tools/changelog-gen", "type": "dev", "tag": ""},
                    {"name": "License Chooser", "link": "/tools/license-chooser", "type": "dev", "tag": ""},
                    {"name": "API Rate Limit Calculator", "link": "/tools/rate-limit-calc", "type": "dev", "tag": ""},
                    {"name": "Code Complexity Estimator", "link": "/tools/complexity", "type": "code", "tag": ""},
                    {"name": "Tech Stack Detector", "link": "/tools/stack-detector", "type": "dev", "tag": ""},
                    {"name": "SQL Schema Generator", "link": "/tools/sql-schema-gen", "type": "code", "tag": ""},
                    {"name": "Database Index Advisor", "link": "/tools/db-index-advisor", "type": "code", "tag": ""},
                    {"name": "JSON to SQL INSERT", "link": "/tools/json-to-sql", "type": "code", "tag": ""},
                    {"name": "ERD Text Generator", "link": "/tools/erd-text", "type": "code", "tag": ""},
                    {"name": "Connection String Builder", "link": "/tools/connection-string", "type": "dev", "tag": ""},
                    {"name": "CSS Grid Generator", "link": "/tools/css-grid", "type": "UX", "tag": ""},
                    {"name": "Bundle Size Estimator", "link": "/tools/bundle-size", "type": "dev", "tag": ""},
                    {"name": "Security Headers Generator", "link": "/tools/security-headers", "type": "Security", "tag": ""},
                    {"name": "LDAP Query Builder", "link": "/tools/ldap-query", "type": "dev", "tag": ""},
                    {"name": "Protocol Buffer Wire Format", "link": "/tools/protobuf-wire", "type": "dev", "tag": ""},
                    {"name": "SAML Request Decoder", "link": "/tools/saml-decoder", "type": "Security", "tag": ""},
                    {"name": "Memory Address Calculator", "link": "/tools/memory-addr", "type": "binary", "tag": ""},
                    {"name": "Prettier Config Generator", "link": "/tools/prettier-config", "type": "dev", "tag": ""},
                    {"name": "Webpack Config Generator", "link": "/tools/webpack-config", "type": "dev", "tag": ""},
                    {"name": "CVSS v3.1 Calculator", "link": "/tools/cvss-calc", "type": "Security", "tag": ""},
                    {"name": "Hash Length Extension", "link": "/tools/hash-length-ext", "type": "Security", "tag": ""},
                    {"name": "CORS Policy Builder", "link": "/tools/cors-builder", "type": "Security", "tag": ""},
                    {"name": "CSP Builder", "link": "/tools/csp-builder", "type": "Security", "tag": ""},
                    {"name": "Bitcoin Address Validator", "link": "/tools/bitcoin-addr", "type": "web3", "tag": ""},
                    {"name": "Ethereum Address Checksum", "link": "/tools/eth-checksum", "type": "web3", "tag": ""},
                    {"name": "IPFS CID Decoder", "link": "/tools/ipfs-cid", "type": "web3", "tag": ""},
                    {"name": "Transaction Fee Calculator", "link": "/tools/tx-fee-calc", "type": "web3", "tag": ""},
                    {"name": "Merkle Tree Visualizer", "link": "/tools/merkle-tree", "type": "web3", "tag": ""},
                    {"name": "Chrome Extension CRX Downloader", "link": "/tools/crx-downloader", "type": "dev", "tag": ""},
                    {"name": "Password Policy Checker", "link": "/tools/password-policy", "type": "Security", "tag": ""},
                    {"name": "Bandwidth Calculator", "link": "/tools/bandwidth", "type": "dev", "tag": ""},
                    {"name": "Age Calculator", "link": "/tools/age-calculator", "type": "date", "tag": ""},
                    {"name": "Environment Variable Validator", "link": "/tools/env-validator", "type": "dev", "tag": ""},
                    {"name": "Cloud Cost Estimator", "link": "/tools/cloud-cost", "type": "dev", "tag": ""},
                    {"name": "Weather Calculator", "link": "/tools/weather-calc", "type": "dev", "tag": ""},
                    {"name": "Cache TTL Calculator", "link": "/tools/cache-ttl", "type": "dev", "tag": ""},
                    {"name": "Modular Arithmetic Calculator", "link": "/tools/modular-arithmetic", "type": "text", "tag": ""},
                    {"name": "Time Duration Calculator", "link": "/tools/duration-calculator", "type": "date", "tag": ""}
                ],
               "color": "lime",
                "titleColor": "limeTitle",
                "typeColor": "limeType" },
    {
        "name": "image",
        "links": [
            {"name": "PNG to JPG", "link": "/image/png-to-jpg", "type": "image", "tag": ""},
            {"name": "JPG to PNG", "link": "/image/jpg-to-png", "type": "image", "tag": ""},
            {"name": "PNG to WebP", "link": "/image/png-to-webp", "type": "image", "tag": ""},
            {"name": "WebP to PNG", "link": "/image/webp-to-png", "type": "image", "tag": ""},
            {"name": "JPG to WebP", "link": "/image/jpg-to-webp", "type": "image", "tag": ""},
            {"name": "SVG to PNG", "link": "/image/svg-to-png", "type": "image", "tag": ""},
            {"name": "HEIC to JPG", "link": "/image/heic-to-jpg", "type": "image", "tag": ""},
            {"name": "Image to Base64", "link": "/image/image-to-base64", "type": "image", "tag": ""},
            {"name": "Base64 to Image", "link": "/image/base64-to-image", "type": "image", "tag": ""},
            {"name": "Background Color Remover", "link": "/image/remove-background", "type": "image", "tag": ""},
            {"name": "Image Resizer", "link": "/image/image-resizer", "type": "image", "tag": ""},
            {"name": "Image Compressor", "link": "/image/image-compressor", "type": "image", "tag": ""},
            {"name": "Image Cropper", "link": "/image/image-cropper", "type": "image", "tag": ""},
            {"name": "Image Rotator", "link": "/image/image-rotator", "type": "image", "tag": ""},
            {"name": "PNG to ICO", "link": "/image/png-to-ico", "type": "image", "tag": ""},
            {"name": "EXIF Viewer", "link": "/image/exif-viewer", "type": "image", "tag": ""},
        ],
        "color": "fuchsia",
        "titleColor": "fuchsiaTitle",
        "typeColor": "fuchsiaType"
    },
    {
        "name": "text",
        "links": [
            {"name": "Online Text Editor", "link": "/text/text-editor", "type": "text", "tag": ""},
            {"name": "Case Converter", "link": "/text/case-converter", "type": "text", "tag": ""},
            {"name": "Word & Character Counter", "link": "/text/word-counter", "type": "text", "tag": ""},
            {"name": "Remove Duplicate Lines", "link": "/text/remove-duplicate-lines", "type": "text", "tag": ""},
            {"name": "Sort Lines", "link": "/text/sort-lines", "type": "text", "tag": ""},
            {"name": "Reverse Text / Lines", "link": "/text/reverse-text", "type": "text", "tag": ""},
            {"name": "Whitespace Remover", "link": "/text/whitespace-remover", "type": "text", "tag": ""},
            {"name": "Regex Find & Replace", "link": "/text/regex-find-replace", "type": "text", "tag": ""},
            {"name": "Text Repeater", "link": "/text/text-repeater", "type": "generator", "tag": ""},
            {"name": "Line Numberer", "link": "/text/line-numberer", "type": "text", "tag": ""},
            {"name": "Indent / Dedent", "link": "/text/indent", "type": "text", "tag": ""},
            {"name": "Column Extractor", "link": "/text/column-extractor", "type": "text", "tag": ""},
            {"name": "Text Truncator", "link": "/text/truncator", "type": "text", "tag": ""},
            {"name": "Emoji Remover", "link": "/text/emoji-remover", "type": "text", "tag": ""},
            {"name": "Word Wrap", "link": "/text/word-wrap", "type": "text", "tag": ""},
            {"name": "Markdown Preview", "link": "/text/markdown-preview", "type": "text", "tag": ""},
            {"name": "Readability Analyzer", "link": "/text/readability", "type": "text", "tag": ""},
            {"name": "Text Alignment", "link": "/text/text-align", "type": "text", "tag": ""},
            {"name": "String Inspector", "link": "/text/string-inspector", "type": "text", "tag": ""},
            {"name": "Unicode Normalizer", "link": "/text/unicode-normalize", "type": "text", "tag": ""},
            {"name": "Text Tokenizer", "link": "/text/tokenizer", "type": "text", "tag": ""},
            {"name": "Text Escape/Unescape", "link": "/text/escape", "type": "text", "tag": ""},
            {"name": "Duplicate Finder", "link": "/text/duplicate-finder", "type": "text", "tag": ""},
            {"name": "Word Frequency Counter", "link": "/text/word-frequency", "type": "text", "tag": ""},
            {"name": "Ordinal Numbers", "link": "/text/ordinal", "type": "text", "tag": ""},
            {"name": "Leet Speak", "link": "/text/leet-speak", "type": "cipher", "tag": ""},
            {"name": "Pig Latin", "link": "/text/pig-latin", "type": "text", "tag": ""},
            {"name": "Palindrome Checker", "link": "/text/palindrome", "type": "text", "tag": ""},
            {"name": "Anagram Checker", "link": "/text/anagram", "type": "text", "tag": ""},
            {"name": "Pangram Checker", "link": "/text/pangram", "type": "text", "tag": ""},
            {"name": "Multi-Case Converter", "link": "/text/multi-case", "type": "text", "tag": ""},
            {"name": "Entity Extractor", "link": "/text/entity-extractor", "type": "text", "tag": ""},
            {"name": "Phonetic Alphabet", "link": "/text/phonetic", "type": "text", "tag": ""},
            {"name": "ASCII Art", "link": "/text/ascii-art", "type": "generator", "tag": ""},
            {"name": "Braille Converter", "link": "/text/braille", "type": "text", "tag": ""},
            {"name": "Scrabble Scorer", "link": "/text/scrabble", "type": "text", "tag": ""},
            {"name": "Wordle Helper", "link": "/text/wordle", "type": "text", "tag": ""},
            {"name": "Regex Flavor Converter", "link": "/text/regex-flavor", "type": "text", "tag": ""},
            {"name": "Anagram Finder", "link": "/text/anagram-finder", "type": "text", "tag": ""},
            {"name": "Homophones", "link": "/text/homophones", "type": "text", "tag": ""},
            {"name": "Readability Grade", "link": "/text/readability-grade", "type": "text", "tag": ""},
            {"name": "Wordplay Generator", "link": "/text/wordplay", "type": "generator", "tag": ""},
            {"name": "Text Similarity", "link": "/text/text-similarity", "type": "text", "tag": ""},
            {"name": "Haiku Validator", "link": "/text/haiku", "type": "text", "tag": ""},
            {"name": "Portmanteau", "link": "/text/portmanteau", "type": "generator", "tag": ""},
            {"name": "Keyboard Layout", "link": "/text/keyboard-layout", "type": "text", "tag": ""},
            {"name": "Slug Generator", "link": "/text/slug-generator", "type": "text", "tag": ""},
            {"name": "Lorem Ipsum Advanced", "link": "/text/lorem-advanced", "type": "generator", "tag": ""},
            {"name": "Soundex & Phonetic Codes", "link": "/text/soundex", "type": "text", "tag": ""},
            {"name": "Levenshtein Distance", "link": "/text/levenshtein", "type": "text", "tag": ""},
            {"name": "Text Entropy Calculator", "link": "/text/text-entropy", "type": "text", "tag": ""},
            {"name": "Text Diff Highlighter", "link": "/text/char-diff", "type": "text", "tag": ""}
        ],
        "color": "rose",
        "titleColor": "roseTitle",
        "typeColor": "roseType"
    },
    {
        "name": "audio",
        "links": [
            {"name": "Audio Converter", "link": "/audio/audio-converter", "type": "audio", "tag": ""},
            {"name": "Audio Trimmer", "link": "/audio/audio-trimmer", "type": "audio", "tag": ""},
            {"name": "Volume Normalizer", "link": "/audio/volume-normalizer", "type": "audio", "tag": ""},
            {"name": "Audio Speed Changer", "link": "/audio/audio-speed", "type": "audio", "tag": ""},
            {"name": "Stereo to Mono", "link": "/audio/stereo-to-mono", "type": "audio", "tag": ""},
            {"name": "Audio Fade In & Out", "link": "/audio/audio-fade", "type": "audio", "tag": ""},
            {"name": "Silence Trimmer", "link": "/audio/silence-trimmer", "type": "audio", "tag": ""},
            {"name": "Audio Joiner", "link": "/audio/audio-joiner", "type": "audio", "tag": ""},
            {"name": "Audio File Info", "link": "/audio/audio-info", "type": "audio", "tag": ""},
            {"name": "Audio Waveform Viewer", "link": "/audio/waveform-viewer", "type": "audio", "tag": ""},
        ],
        "color": "violet",
        "titleColor": "violetTitle",
        "typeColor": "violetType"
    },
    {
        "name": "pdf",
        "links": [
            {"name": "Merge PDFs", "link": "/pdf/pdf-merge", "type": "pdf", "tag": ""},
            {"name": "Split PDF", "link": "/pdf/pdf-split", "type": "pdf", "tag": ""},
            {"name": "PDF to Images", "link": "/pdf/pdf-to-images", "type": "pdf", "tag": ""},
            {"name": "Images to PDF", "link": "/pdf/images-to-pdf", "type": "pdf", "tag": ""},
            {"name": "PDF to Text", "link": "/pdf/pdf-to-text", "type": "pdf", "tag": ""},
            {"name": "Rotate & Organize PDF", "link": "/pdf/pdf-organize", "type": "pdf", "tag": ""},
            {"name": "Watermark PDF", "link": "/pdf/pdf-watermark", "type": "pdf", "tag": ""},
            {"name": "Add Page Numbers", "link": "/pdf/pdf-page-numbers", "type": "pdf", "tag": ""},
            {"name": "Resize PDF Pages", "link": "/pdf/pdf-resize", "type": "pdf", "tag": ""},
            {"name": "PDF Metadata Editor", "link": "/pdf/pdf-metadata", "type": "pdf", "tag": ""},
            {"name": "Flatten PDF Forms", "link": "/pdf/pdf-flatten", "type": "pdf", "tag": ""},
            {"name": "PDF Info", "link": "/pdf/pdf-info", "type": "pdf", "tag": ""},
            {"name": "PDF Layer Exporter", "link": "/pdf/pdf-layers", "type": "pdf", "tag": ""},
        ],
        "color": "red",
        "titleColor": "redTitle",
        "typeColor": "redType"
    },
    {
        "name": "network",
        "links": [
            {"name": "IPv4 to Integer", "link": "/network/ipv4-to-integer", "type": "network", "tag": ""},
            {"name": "IPv4 to Binary", "link": "/network/ipv4-to-binary", "type": "network", "tag": ""},
            {"name": "CIDR Calculator", "link": "/network/cidr-calculator", "type": "network", "tag": ""},
            {"name": "IPv6 Expander", "link": "/network/ipv6", "type": "network", "tag": ""},
            {"name": "URL Parser", "link": "/network/url-parser", "type": "network", "tag": ""},
            {"name": "IP Classifier", "link": "/network/ip-classifier", "type": "network", "tag": ""},
            {"name": "Cookie Parser", "link": "/network/cookie-parser", "type": "network", "tag": ""},
            {"name": "MAC Address", "link": "/network/mac-address", "type": "network", "tag": ""},
            {"name": "Subnet List", "link": "/network/subnet-list", "type": "network", "tag": ""},
            {"name": "Curl to Fetch", "link": "/network/curl-to-fetch", "type": "network", "tag": ""},
            {"name": "HTTP Request Builder", "link": "/network/http-request", "type": "network", "tag": ""},
            {"name": "IPv4/IPv6 Mapping", "link": "/network/ip-mapping", "type": "network", "tag": ""},
            {"name": "TLS Cipher Suites", "link": "/network/tls-cipher", "type": "network", "tag": ""},
            {"name": "URI Template", "link": "/network/uri-template", "type": "network", "tag": ""},
            {"name": "Content-Type Builder", "link": "/network/content-type", "type": "network", "tag": ""},
            {"name": "WebSocket Frame", "link": "/network/ws-frame", "type": "network", "tag": ""},
            {"name": "OAuth 2.0 Flow", "link": "/network/oauth-flow", "type": "network", "tag": ""},
            {"name": "Packet Size Calc", "link": "/network/packet-size", "type": "network", "tag": ""},
            {"name": "Email Header Analyzer", "link": "/network/email-headers", "type": "network", "tag": ""},
            {"name": "HTTP/2 Frame", "link": "/network/http2-frame", "type": "network", "tag": ""},
            {"name": "DoH Query Builder", "link": "/network/doh-simulator", "type": "network", "tag": ""},
            {"name": "VLSM Calculator", "link": "/network/vlsm", "type": "network", "tag": ""},
            {"name": "TLS Config Generator", "link": "/network/tls-config", "type": "network", "tag": ""},
            {"name": "IP Subnet Calculator", "link": "/network/subnet-calc", "type": "network", "tag": ""},
            {"name": "NTP Time Calculator", "link": "/network/ntp-time", "type": "network", "tag": ""},
            {"name": "URL Builder", "link": "/network/url-builder", "type": "network", "tag": ""}
        ],
        "color": "sky",
        "titleColor": "skyTitle",
        "typeColor": "skyType"
    }
]
