import CryptoJS from 'crypto-js';
import {
  sha3_224,
  sha3_256,
  sha3_384,
  sha3_512,
  keccak224,
  keccak256,
  keccak384,
  keccak512,
} from 'js-sha3';
import { Operation } from '../types';

const keyParam = {
  id: 'key',
  label: 'Secret Key',
  kind: 'text' as const,
  default: '',
};

export const hashingOperations: Operation[] = [
  {
    id: 'md5',
    name: 'MD5',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.MD5(input).toString(),
  },
  {
    id: 'sha1',
    name: 'SHA1',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.SHA1(input).toString(),
  },
  {
    id: 'sha224',
    name: 'SHA224',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.SHA224(input).toString(),
  },
  {
    id: 'sha256',
    name: 'SHA256',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.SHA256(input).toString(),
  },
  {
    id: 'sha384',
    name: 'SHA384',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.SHA384(input).toString(),
  },
  {
    id: 'sha512',
    name: 'SHA512',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.SHA512(input).toString(),
  },
  {
    id: 'sha3-224',
    name: 'SHA3-224',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => sha3_224(input),
  },
  {
    id: 'sha3-256',
    name: 'SHA3-256',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => sha3_256(input),
  },
  {
    id: 'sha3-384',
    name: 'SHA3-384',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => sha3_384(input),
  },
  {
    id: 'sha3-512',
    name: 'SHA3-512',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => sha3_512(input),
  },
  {
    id: 'keccak224',
    name: 'Keccak-224',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => keccak224(input),
  },
  {
    id: 'keccak256',
    name: 'Keccak-256',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => keccak256(input),
  },
  {
    id: 'keccak384',
    name: 'Keccak-384',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => keccak384(input),
  },
  {
    id: 'keccak512',
    name: 'Keccak-512',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => keccak512(input),
  },
  {
    id: 'ripemd160',
    name: 'RIPEMD160',
    category: 'hashing',
    params: [],
    chainable: true,
    fn: (input) => CryptoJS.RIPEMD160(input).toString(),
  },
  {
    id: 'hmac-md5',
    name: 'HMAC-MD5',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacMD5(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha1',
    name: 'HMAC-SHA1',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA1(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha224',
    name: 'HMAC-SHA224',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA224(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha256',
    name: 'HMAC-SHA256',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA256(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha384',
    name: 'HMAC-SHA384',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA384(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha512',
    name: 'HMAC-SHA512',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA512(input, params.key || '').toString(),
  },
  {
    id: 'hmac-sha3',
    name: 'HMAC-SHA3',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacSHA3(input, params.key || '').toString(),
  },
  {
    id: 'hmac-ripemd160',
    name: 'HMAC-RIPEMD160',
    category: 'hashing',
    params: [keyParam],
    chainable: true,
    fn: (input, params) => CryptoJS.HmacRIPEMD160(input, params.key || '').toString(),
  },
];
