import {
  convertCase,
  removeDuplicateLines,
  sortLinesAsc, sortLinesDesc,
  reverseString, reverseLines,
  toSlug,
  trimLines, collapseSpaces, removeBlankLines,
  regexFindReplace,
} from '@/Components/Functions/TextUtilities/logic';
import { Operation } from '../types';

export const textUtilsOperations: Operation[] = [
  {
    id: 'case-convert',
    name: 'Case Converter',
    category: 'text',
    params: [
      {
        id: 'case',
        label: 'Case',
        kind: 'select',
        options: [
          { value: 'upper', label: 'UPPER' },
          { value: 'lower', label: 'lower' },
          { value: 'title', label: 'Title' },
          { value: 'camel', label: 'camelCase' },
          { value: 'snake', label: 'snake_case' },
          { value: 'kebab', label: 'kebab-case' },
          { value: 'pascal', label: 'PascalCase' },
        ],
        default: 'lower',
      },
    ],
    chainable: true,
    fn: (input, p) => convertCase(input, p.case ?? 'lower'),
  },
  {
    id: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => removeDuplicateLines(input),
  },
  {
    id: 'sort-lines-asc',
    name: 'Sort Lines A\u2192Z',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => sortLinesAsc(input),
  },
  {
    id: 'sort-lines-desc',
    name: 'Sort Lines Z\u2192A',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => sortLinesDesc(input),
  },
  {
    id: 'reverse-text',
    name: 'Reverse Text',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => reverseString(input),
  },
  {
    id: 'reverse-lines',
    name: 'Reverse Lines',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => reverseLines(input),
  },
  {
    id: 'to-slug',
    name: 'Text to Slug',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => toSlug(input),
  },
  {
    id: 'trim-lines',
    name: 'Trim Lines',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => trimLines(input),
  },
  {
    id: 'collapse-spaces',
    name: 'Collapse Spaces',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => collapseSpaces(input),
  },
  {
    id: 'remove-blank-lines',
    name: 'Remove Blank Lines',
    category: 'text',
    params: [],
    chainable: true,
    fn: (input) => removeBlankLines(input),
  },
  {
    id: 'regex-replace',
    name: 'Regex Find & Replace',
    category: 'text',
    params: [
      {
        id: 'pattern',
        label: 'Pattern',
        kind: 'text',
        default: '',
      },
      {
        id: 'flags',
        label: 'Flags',
        kind: 'text',
        default: 'g',
      },
      {
        id: 'replacement',
        label: 'Replacement',
        kind: 'text',
        default: '',
      },
    ],
    chainable: true,
    fn: (input, p) => regexFindReplace(input, p.pattern ?? '', p.flags ?? 'g', p.replacement ?? ''),
  },
];
