'use client';

import { useState, useEffect, useRef } from 'react';
import Panel from '@/Components/MainView/MainPanel/Panel';
import {
  decodeJwtParts,
  signJwt,
  verifyJwt,
  generateKeyPair,
  algFamily,
  isAsymmetric,
  keyGroup,
  ALL_ALGORITHMS,
  type JwtAlgorithm,
} from './logic';

const DEFAULT_HEADER = JSON.stringify({ alg: 'HS256', typ: 'JWT' }, null, 2);
const DEFAULT_PAYLOAD = JSON.stringify(
  { sub: '1234567890', name: 'John Doe', iat: 1516239022 },
  null,
  2
);
const DEFAULT_SECRET = 'your-256-bit-secret';

const ALG_GROUPS: { label: string; algs: JwtAlgorithm[] }[] = [
  { label: 'HMAC (symmetric)', algs: ['HS256', 'HS384', 'HS512'] },
  { label: 'RSA', algs: ['RS256', 'RS384', 'RS512'] },
  { label: 'RSA-PSS', algs: ['PS256', 'PS384', 'PS512'] },
  { label: 'ECDSA', algs: ['ES256', 'ES384', 'ES512'] },
  { label: 'EdDSA', algs: ['EdDSA'] },
  { label: 'Unsecured', algs: ['none'] },
];

type KeyOverrides = { s?: string; priv?: string; pub?: string };

export function JwtEditor() {
  const [token, setToken] = useState('');
  const [header, setHeader] = useState(DEFAULT_HEADER);
  const [payload, setPayload] = useState(DEFAULT_PAYLOAD);
  const [secret, setSecret] = useState(DEFAULT_SECRET);
  const [privateKey, setPrivateKey] = useState('');
  const [publicKey, setPublicKey] = useState('');
  const [algorithm, setAlgorithm] = useState<JwtAlgorithm>('HS256');
  const [decodeError, setDecodeError] = useState('');
  const [encodeError, setEncodeError] = useState('');
  const [keyError, setKeyError] = useState('');
  const [verified, setVerified] = useState<boolean | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  // Tracks which key group (RSA / P-256 / Ed25519 …) the current keys belong to and
  // whether they were auto-generated, so we can regenerate sample keys on a group
  // change without ever discarding keys the user pasted in.
  const [keyGroupState, setKeyGroupState] = useState('');
  const [keysAutoGenerated, setKeysAutoGenerated] = useState(false);

  // Latest-wins guard: WebCrypto is async, so a slow sign/verify must not overwrite
  // the result of a newer edit. Each async op captures an id and bails if superseded.
  const reqId = useRef(0);

  // The colour-coded highlight layer sits behind the encoded textarea; keep its scroll
  // position in sync so the colours stay aligned with the (transparent) text on top.
  const overlayRef = useRef<HTMLDivElement>(null);

  // Re-sign the decoded parts and reflect the verification state.
  const resign = async (h: string, p: string, alg: JwtAlgorithm, o: KeyOverrides = {}) => {
    const fam = algFamily(alg);
    const signKey = fam === 'HMAC' ? (o.s ?? secret) : (o.priv ?? privateKey);
    const verifyKey = fam === 'HMAC' ? (o.s ?? secret) : (o.pub ?? publicKey);
    const id = ++reqId.current;
    try {
      const t = await signJwt(h, p, signKey, alg);
      if (id !== reqId.current) return;
      setToken(t);
      setEncodeError('');
      setDecodeError('');
      if (fam === 'none') {
        setVerified(null);
        return;
      }
      const ok = await verifyJwt(t, verifyKey, alg);
      if (id !== reqId.current) return;
      setVerified(ok);
    } catch (e) {
      if (id !== reqId.current) return;
      setEncodeError((e as Error).message);
      setVerified(null);
    }
  };

  // Verify the token that is currently in the Encoded box, without re-signing it.
  // Used whenever a key changes: a pasted token must keep its original signature so
  // the user can see whether the key they typed actually matches it.
  const reverify = async (tok: string, alg: JwtAlgorithm, o: KeyOverrides = {}) => {
    const fam = algFamily(alg);
    if (!tok.trim() || fam === 'none') {
      setVerified(null);
      return;
    }
    const verifyKey = fam === 'HMAC' ? (o.s ?? secret) : (o.pub ?? publicKey);
    const id = ++reqId.current;
    try {
      const ok = await verifyJwt(tok, verifyKey, alg);
      if (id !== reqId.current) return;
      setVerified(ok);
      setKeyError('');
    } catch (e) {
      // An unreadable key (half-typed PEM, malformed JWK) can't verify anything.
      if (id !== reqId.current) return;
      setVerified(false);
      setKeyError((e as Error).message);
    }
  };

  // Decode an edited encoded token back into its parts and verify it.
  const redecode = async (value: string, o: KeyOverrides = {}) => {
    if (!value.trim()) {
      setDecodeError('');
      setVerified(null);
      return;
    }
    let parts;
    try {
      parts = decodeJwtParts(value);
    } catch (e) {
      setDecodeError((e as Error).message);
      setVerified(null);
      return;
    }
    setHeader(parts.header);
    setPayload(parts.payload);
    const alg = parts.algorithm ?? algorithm;
    if (parts.algorithm) setAlgorithm(parts.algorithm);
    setDecodeError('');
    setEncodeError('');

    const fam = algFamily(alg);
    if (fam === 'none') {
      setVerified(null);
      return;
    }
    const verifyKey = fam === 'HMAC' ? (o.s ?? secret) : (o.pub ?? publicKey);
    const id = ++reqId.current;
    try {
      const ok = await verifyJwt(value, verifyKey, alg);
      if (id !== reqId.current) return;
      setVerified(ok);
      setKeyError('');
    } catch (e) {
      if (id !== reqId.current) return;
      setVerified(false);
      setKeyError((e as Error).message);
    }
  };

  // Generate a fresh key pair for the algorithm, then re-sign with it.
  const generateAndResign = async (h: string, p: string, alg: JwtAlgorithm) => {
    setGenerating(true);
    setKeyError('');
    try {
      const { privateKey: priv, publicKey: pub } = await generateKeyPair(alg);
      setPrivateKey(priv);
      setPublicKey(pub);
      setKeyGroupState(keyGroup(alg));
      setKeysAutoGenerated(true);
      await resign(h, p, alg, { priv, pub });
    } catch (e) {
      setKeyError((e as Error).message);
      setVerified(null);
    } finally {
      setGenerating(false);
    }
  };

  // Initial token + ?from= pre-population. The sign2n tool deep-links here with
  // ?alg=HS256&secret=<recovered PEM> to set up an RS→HS confusion forgery: it
  // loads the token's payload, forces the HMAC alg, and re-signs with the key as
  // the secret. A plain ?secret= (no alg) just prefills the HMAC secret field.
  useEffect(() => {
    const params = new URLSearchParams(
      typeof window !== 'undefined' ? window.location.search : ''
    );
    const from = params.get('from');
    const algParam = params.get('alg');
    const secretParam = params.get('secret');
    const forgeAlg =
      algParam && (ALL_ALGORITHMS as string[]).includes(algParam)
        ? (algParam as JwtAlgorithm)
        : null;

    if (from && forgeAlg && algFamily(forgeAlg) === 'HMAC') {
      let parts;
      try {
        parts = decodeJwtParts(from);
      } catch {
        setToken(from);
        redecode(from);
        return;
      }
      let nextHeader = parts.header;
      try {
        const parsed = JSON.parse(parts.header);
        parsed.alg = forgeAlg;
        nextHeader = JSON.stringify(parsed, null, 2);
      } catch {
        /* keep header as-is if it isn't valid JSON */
      }
      const sec = secretParam ?? secret;
      setHeader(nextHeader);
      setPayload(parts.payload);
      setAlgorithm(forgeAlg);
      if (secretParam) setSecret(secretParam);
      resign(nextHeader, parts.payload, forgeAlg, { s: sec });
    } else if (from) {
      setToken(from);
      if (secretParam) setSecret(secretParam);
      redecode(from, secretParam ? { s: secretParam } : {});
    } else {
      resign(DEFAULT_HEADER, DEFAULT_PAYLOAD, 'HS256');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onTokenChange = (value: string) => {
    setToken(value);
    redecode(value);
  };

  const onHeaderChange = (value: string) => {
    setHeader(value);
    resign(value, payload, algorithm);
  };

  const onPayloadChange = (value: string) => {
    setPayload(value);
    resign(header, value, algorithm);
  };

  // Key edits never rewrite the encoded token — they only re-check it, so a pasted
  // token keeps its original signature and reports "Invalid Signature" until the key
  // matches. The "Update encoded token" button re-signs with the current key.
  const onSecretChange = (value: string) => {
    setSecret(value);
    reverify(token, algorithm, { s: value });
  };

  const onPrivateKeyChange = (value: string) => {
    setPrivateKey(value);
    setKeysAutoGenerated(false);
    setKeyGroupState('');
    // The private key only signs — nothing to re-check until the token is re-signed.
  };

  const onPublicKeyChange = (value: string) => {
    setPublicKey(value);
    setKeysAutoGenerated(false);
    setKeyGroupState('');
    reverify(token, algorithm, { pub: value });
  };

  const copyToken = () => {
    if (!token || typeof navigator === 'undefined' || !navigator.clipboard) return;
    navigator.clipboard.writeText(token).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  // Pretty-print a JSON field once the user leaves it. Whitespace doesn't affect the
  // signed token (it re-serialises), so this is purely cosmetic and safe to skip on
  // invalid JSON, which we leave untouched so the user can keep fixing it.
  const formatJsonField = (value: string, setter: (v: string) => void) => {
    try {
      const formatted = JSON.stringify(JSON.parse(value), null, 2);
      if (formatted !== value) setter(formatted);
    } catch (_e) {
      /* leave invalid JSON as-is */
    }
  };

  const onAlgorithmChange = (alg: JwtAlgorithm) => {
    // Keep the header's alg field in sync.
    let nextHeader = header;
    try {
      const parsed = JSON.parse(header);
      parsed.alg = alg;
      nextHeader = JSON.stringify(parsed, null, 2);
      setHeader(nextHeader);
    } catch (_e) {
      /* leave header as-is if it isn't valid JSON */
    }
    setAlgorithm(alg);

    const needNewKeys =
      isAsymmetric(alg) &&
      (!privateKey.trim() ||
        !publicKey.trim() ||
        (keysAutoGenerated && keyGroupState !== keyGroup(alg)));

    if (needNewKeys) {
      generateAndResign(nextHeader, payload, alg);
    } else {
      resign(nextHeader, payload, alg);
    }
  };

  const labelClass = 'text-xs font-bold uppercase tracking-wider';
  // Base field styling without a resize rule — each field picks its own below, so the
  // two rules never fight for precedence in the generated stylesheet.
  const inputBase =
    'bg-white text-gray-900 placeholder:text-gray-400 p-3 w-full border border-gray-300 focus:border-gray-900 focus:outline-none font-mono text-sm';
  const inputClass = `${inputBase} resize-none`;
  // Header/Payload are drag-to-grow: JSON payloads vary wildly in length.
  const growableClass = `${inputBase} resize-y`;

  const family = algFamily(algorithm);
  const asymmetric = isAsymmetric(algorithm);
  const verifyKeyMissing = asymmetric && !publicKey.trim();
  const tokenParts = token.split('.');

  // Banner appearance/text.
  let bannerClass = 'bg-gray-50 border-gray-300 text-gray-500';
  let bannerText = '— Edit the token or its parts to begin';
  if (algorithm === 'none') {
    bannerClass = 'bg-amber-50 border-amber-300 text-amber-700';
    bannerText = '⚠ Unsigned token (alg: none) — no signature to verify';
  } else if (verifyKeyMissing) {
    bannerText = '— Provide a public key to verify the signature';
  } else if (verified === true) {
    bannerClass = 'bg-emerald-50 border-emerald-300 text-emerald-700';
    bannerText = '✓ Signature Verified';
  } else if (verified === false) {
    bannerClass = 'bg-red-50 border-red-300 text-red-700';
    bannerText = '✗ Invalid Signature';
  }

  const content = (
    <div className="flex flex-col gap-6">
      {/* Signature status banner */}
      <div className={`border px-4 py-2.5 text-xs font-bold uppercase tracking-wider ${bannerClass}`}>
        {bannerText}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Encoded column — the textarea text is transparent and the colour-coded
            highlight layer behind it renders the actual (per-part coloured) token. */}
        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between gap-2">
            <label className={`${labelClass} text-gray-500`}>Encoded</label>
            <button
              onClick={copyToken}
              disabled={!token}
              className={`px-3 py-1 text-xs font-bold uppercase tracking-wider border transition-colors ${
                token
                  ? 'bg-white text-gray-700 border-gray-200 hover:bg-gray-50 hover:border-gray-900 cursor-pointer'
                  : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
              }`}
            >
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          {/* bg lives on the wrapper: the textarea itself must stay transparent so the
              colour-coded layer shows through, but the box still needs the same field
              background as the Header/Payload panes. */}
          <div className="relative bg-white">
            <div
              ref={overlayRef}
              aria-hidden="true"
              className="jwt-encoded-view absolute inset-0 p-3 w-full border border-transparent font-mono text-sm leading-5 whitespace-pre-wrap break-all [overflow-wrap:break-word] [scrollbar-gutter:stable] overflow-hidden pointer-events-none"
            >
              {tokenParts.length === 3 ? (
                <>
                  <span className="text-red-500">{tokenParts[0]}</span>
                  <span className="text-gray-400">.</span>
                  <span className="text-fuchsia-600">{tokenParts[1]}</span>
                  <span className="text-gray-400">.</span>
                  <span className="text-sky-600">{tokenParts[2]}</span>
                </>
              ) : (
                <span className="text-gray-900">{token}</span>
              )}
            </div>
            <textarea
              rows={10}
              // `block` matters: as an inline element the textarea would sit on a text
              // baseline, leaving the wrapper a few pixels taller than the box and the
              // overlay spilling its last line below the bottom border.
              className="jwt-encoded-input relative block p-3 w-full border border-gray-300 focus:border-gray-900 focus:outline-none font-mono text-sm leading-5 resize-y break-all [scrollbar-gutter:stable] placeholder:text-gray-400"
              value={token}
              onChange={e => onTokenChange(e.target.value)}
              onScroll={e => {
                const o = overlayRef.current;
                if (o) {
                  o.scrollTop = e.currentTarget.scrollTop;
                  o.scrollLeft = e.currentTarget.scrollLeft;
                }
              }}
              placeholder="Paste a JWT token here, or edit the decoded parts on the right…"
              spellCheck={false}
            />
          </div>
          {decodeError && (
            <p className="text-red-600 text-xs font-mono">{decodeError}</p>
          )}
        </div>

        {/* Decoded column */}
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <label className={`${labelClass} text-red-500`}>Header</label>
            <textarea
              rows={4}
              className={growableClass}
              value={header}
              onChange={e => onHeaderChange(e.target.value)}
              onBlur={() => formatJsonField(header, setHeader)}
              spellCheck={false}
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className={`${labelClass} text-fuchsia-600`}>Payload</label>
            <textarea
              rows={6}
              className={growableClass}
              value={payload}
              onChange={e => onPayloadChange(e.target.value)}
              onBlur={() => formatJsonField(payload, setPayload)}
              spellCheck={false}
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className={`${labelClass} text-sky-600`}>
              {algorithm === 'none' ? 'Signature' : asymmetric ? 'Sign & Verify (key pair)' : 'Verify Signature'}
            </label>

            {/* Algorithm selector */}
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-gray-400 text-xs">Algorithm:</span>
              <select
                value={algorithm}
                onChange={e => onAlgorithmChange(e.target.value as JwtAlgorithm)}
                className="bg-white text-gray-900 border border-gray-300 focus:border-gray-900 focus:outline-none px-3 py-1.5 text-xs font-mono cursor-pointer"
              >
                {ALG_GROUPS.map(group => (
                  <optgroup key={group.label} label={group.label}>
                    {group.algs.map(alg => (
                      <option key={alg} value={alg}>
                        {alg}
                      </option>
                    ))}
                  </optgroup>
                ))}
              </select>
            </div>

            {/* HMAC: single secret */}
            {family === 'HMAC' && (
              <>
                <textarea
                  // Auto-grow: start one line tall and expand to fit any newlines the
                  // user types/pastes, re-measured after every value change.
                  ref={el => {
                    if (el) {
                      el.style.height = 'auto';
                      el.style.height = `${el.scrollHeight}px`;
                    }
                  }}
                  rows={1}
                  className={`${inputClass} overflow-hidden`}
                  value={secret}
                  onChange={e => onSecretChange(e.target.value)}
                  placeholder={'Secret key (HMAC) — plain text, or an oct JWK {"kty":"oct","k":"…"}'}
                  spellCheck={false}
                />
                <p className="text-gray-400 text-xs">
                  Paste an <code className="font-mono">oct</code> JWK to use a raw/binary key — its
                  base64url <code className="font-mono">k</code> value is decoded to the exact secret
                  bytes (text secrets keep working as before).
                </p>
                <div className="bg-amber-50 border border-amber-300 px-3 py-2.5 text-amber-800 text-xs leading-relaxed">
                  <span className="font-bold">⚠ Brute-forceable.</span> HMAC algorithms (
                  <code className="font-mono">HS256/384/512</code>) sign with a shared secret. A
                  short or dictionary-word secret can be cracked offline in seconds — use a long,
                  random secret (32+ bytes) and never commit it to source control.
                </div>
              </>
            )}

            {/* Asymmetric: private + public key pair */}
            {asymmetric && (
              <>
                <div className="flex items-center gap-3 flex-wrap">
                  <button
                    onClick={() => generateAndResign(header, payload, algorithm)}
                    disabled={generating}
                    className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider border transition-colors cursor-pointer ${
                      generating
                        ? 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
                        : 'bg-gray-900 text-white border-gray-900 hover:bg-gray-700'
                    }`}
                  >
                    {generating ? 'Generating…' : 'Generate new key pair'}
                  </button>
                  <span className="text-gray-400 text-xs">PEM or JWK accepted</span>
                </div>
                <div className="flex flex-col gap-2">
                  <label className={`${labelClass} text-gray-500`}>Private Key (signing)</label>
                  <textarea
                    rows={5}
                    className={inputClass}
                    value={privateKey}
                    onChange={e => onPrivateKeyChange(e.target.value)}
                    placeholder={'-----BEGIN PRIVATE KEY-----  ...  or  {"kty": ...} (JWK)'}
                    spellCheck={false}
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label className={`${labelClass} text-gray-500`}>Public Key (verifying)</label>
                  <textarea
                    rows={4}
                    className={inputClass}
                    value={publicKey}
                    onChange={e => onPublicKeyChange(e.target.value)}
                    placeholder={'-----BEGIN PUBLIC KEY-----  ...  or  {"kty": ...} (JWK)'}
                    spellCheck={false}
                  />
                </div>
                {algorithm === 'EdDSA' && (
                  <p className="text-gray-400 text-xs">
                    EdDSA uses Ed25519 — requires a recent browser (Chrome/Edge 137+, Firefox,
                    Safari 17+).
                  </p>
                )}
              </>
            )}

            {/* none: insecure-by-design */}
            {algorithm === 'none' && (
              <div className="bg-red-50 border border-red-300 px-3 py-2.5 text-red-700 text-xs leading-relaxed">
                <span className="font-bold">⚠ Insecure by design.</span> The{' '}
                <code className="font-mono">none</code> algorithm strips the signature, so anyone
                can tamper with the header and payload and forge valid-looking tokens. It exists
                only for testing — never accept or issue <code className="font-mono">none</code>{' '}
                tokens in a production environment.
              </div>
            )}

            {/* Explicit re-sign. Changing a key never rewrites the encoded token on its
                own, so a pasted token keeps its signature until the user asks for a new
                one here. */}
            <div className="flex items-center gap-3 flex-wrap pt-1">
              <button
                onClick={() => resign(header, payload, algorithm)}
                disabled={generating}
                className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider border transition-colors ${
                  generating
                    ? 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
                    : 'bg-gray-900 text-white border-gray-900 hover:bg-gray-700 cursor-pointer'
                }`}
              >
                Update encoded token
              </button>
              <span className="text-gray-400 text-xs">
                {verified === false
                  ? 'Signature does not match this key — re-sign to replace the token.'
                  : 'Re-signs the token with the key above.'}
              </span>
            </div>

            {keyError && <p className="text-red-600 text-xs font-mono">{keyError}</p>}
            {encodeError && <p className="text-red-600 text-xs font-mono">{encodeError}</p>}
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <Panel
      title="JWT Editor"
      description="Decode, edit, and re-sign [1 JSON Web Tokens 2] live. Edit the encoded token on the left or the [1 header 2] and [1 payload 2] on the right — the other side updates instantly. Changing a key only re-checks the signature, so a pasted token keeps its own; press [1 Update encoded token 2] to re-sign with it. Signs and verifies HMAC ([1 HS256 2]), RSA (RS/PS), ECDSA (ES) and EdDSA, with PEM or JWK keys, entirely in your browser."
      backColor="yellow"
      extraElements={content}
    />
  );
}
