// ─── Gitignore Generator Logic ────────────────────────────────────────────────

export type ProjectType = {
  id: string;
  label: string;
  patterns: string[];
};

export const PROJECT_TYPES: ProjectType[] = [
  {
    id: 'node',
    label: 'Node.js',
    patterns: [
      '# Node.js',
      'node_modules/',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'pnpm-debug.log*',
      '.npm',
      '.yarn-integrity',
      'package-lock.json',
      'yarn.lock',
      '.pnp.*',
      '.env',
      '.env.local',
      '.env.*.local',
    ],
  },
  {
    id: 'python',
    label: 'Python',
    patterns: [
      '# Python',
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '*.pyo',
      '.Python',
      'build/',
      'develop-eggs/',
      'dist/',
      'downloads/',
      'eggs/',
      '.eggs/',
      'lib/',
      'lib64/',
      'parts/',
      'sdist/',
      'var/',
      'wheels/',
      '*.egg-info/',
      '.installed.cfg',
      '*.egg',
      'MANIFEST',
      '.env',
      '.venv',
      'env/',
      'venv/',
      'ENV/',
      'env.bak/',
      'venv.bak/',
      '.pytest_cache/',
      '.mypy_cache/',
      '.ruff_cache/',
      'htmlcov/',
      '.tox/',
      '.coverage',
      '.coverage.*',
      'coverage.xml',
      '*.cover',
    ],
  },
  {
    id: 'go',
    label: 'Go',
    patterns: [
      '# Go',
      '*.exe',
      '*.exe~',
      '*.dll',
      '*.so',
      '*.dylib',
      '*.test',
      '*.out',
      'go.sum',
      'vendor/',
      '/bin/',
      '/tmp/',
    ],
  },
  {
    id: 'rust',
    label: 'Rust',
    patterns: [
      '# Rust',
      '/target/',
      'Cargo.lock',
      '**/*.rs.bk',
      '*.pdb',
    ],
  },
  {
    id: 'java',
    label: 'Java',
    patterns: [
      '# Java',
      '*.class',
      '*.log',
      '*.ctxt',
      '.mtj.tmp/',
      '*.jar',
      '*.war',
      '*.nar',
      '*.ear',
      '*.zip',
      '*.tar.gz',
      '*.rar',
      'hs_err_pid*',
      'replay_pid*',
    ],
  },
  {
    id: 'dotnet',
    label: '.NET / C#',
    patterns: [
      '# .NET',
      'bin/',
      'obj/',
      '*.user',
      '*.suo',
      '*.userosscache',
      '*.sln.docstates',
      '.vs/',
      '_UpgradeReport_Files/',
      'Backup*/',
      'UpgradeLog*.XML',
      'UpgradeLog*.htm',
      'ServiceFabricBackup/',
      '*.publishsettings',
      '*.nupkg',
      '*.snupkg',
      '*.nuget.props',
      '*.nuget.targets',
      'packages/',
      '!**/packages/build/',
      '*.lock.json',
    ],
  },
  {
    id: 'react',
    label: 'React / Next.js',
    patterns: [
      '# React / Next.js',
      '.next/',
      'out/',
      'build/',
      '.turbo/',
      '*.tsbuildinfo',
      '.vercel',
      '.env*.local',
    ],
  },
  {
    id: 'django',
    label: 'Django',
    patterns: [
      '# Django',
      '*.log',
      '*.pot',
      '*.pyc',
      '__pycache__/',
      'local_settings.py',
      'db.sqlite3',
      'db.sqlite3-journal',
      'media/',
      'staticfiles/',
      '.env',
    ],
  },
  {
    id: 'rails',
    label: 'Ruby on Rails',
    patterns: [
      '# Ruby on Rails',
      '*.rbc',
      '/tmp/',
      '/log/',
      '/.bundle/',
      '/vendor/bundle',
      '/public/system',
      '/public/uploads',
      '.env',
      '/config/master.key',
      '/config/credentials/*.key',
      '/storage/*',
      '!/storage/.keep',
      '/public/assets',
      '.byebug_history',
      'node_modules/',
      '/yarn-error.log',
    ],
  },
  {
    id: 'flutter',
    label: 'Flutter / Dart',
    patterns: [
      '# Flutter / Dart',
      '.dart_tool/',
      '.flutter-plugins',
      '.flutter-plugins-dependencies',
      '.packages',
      '.pub-cache/',
      '.pub/',
      '/build/',
      '*.iml',
      '*.ipr',
      '*.iws',
      '.idea/',
      '*.g.dart',
      '*.freezed.dart',
    ],
  },
  {
    id: 'php',
    label: 'PHP / Laravel',
    patterns: [
      '# PHP / Laravel',
      '/vendor/',
      '/node_modules/',
      '/public/hot',
      '/public/storage',
      '/storage/*.key',
      '.env',
      '.env.backup',
      '.phpunit.result.cache',
      'Homestead.json',
      'Homestead.yaml',
      'auth.json',
      '/bootstrap/ssr/',
      '/.phpunit.cache',
    ],
  },
  {
    id: 'swift',
    label: 'Swift / Xcode',
    patterns: [
      '# Swift / Xcode',
      '*.xcodeproj/*',
      '!*.xcodeproj/project.pbxproj',
      '!*.xcodeproj/xcshareddata/',
      '!*.xcworkspace/contents.xcworkspacedata',
      '/*.gcno',
      '**/xcshareddata/WorkspaceSettings.xcsettings',
      '.build/',
      '*.resolved',
      'DerivedData/',
      '*.moved-aside',
      '*.playground',
    ],
  },
  {
    id: 'android',
    label: 'Android',
    patterns: [
      '# Android',
      '*.iml',
      '.gradle/',
      '/local.properties',
      '/.idea/',
      '.DS_Store',
      '/build/',
      '/captures/',
      '.externalNativeBuild/',
      '.cxx/',
      '*.apk',
      '*.aab',
      '*.ap_',
      'google-services.json',
      'keystore.properties',
    ],
  },
  {
    id: 'macos',
    label: 'macOS',
    patterns: [
      '# macOS',
      '.DS_Store',
      '.AppleDouble',
      '.LSOverride',
      'Icon\r',
      '._*',
      '.DocumentRevisions-V100',
      '.fseventsd',
      '.Spotlight-V100',
      '.TemporaryItems',
      '.Trashes',
      '.VolumeIcon.icns',
      '.com.apple.timemachine.donotpresent',
      '.AppleDB',
      '.AppleDesktop',
      'Network Trash Folder',
      'Temporary Items',
      '.apdisk',
    ],
  },
  {
    id: 'windows',
    label: 'Windows',
    patterns: [
      '# Windows',
      'Thumbs.db',
      'Thumbs.db:encryptable',
      'ehthumbs.db',
      'ehthumbs_vista.db',
      '*.stackdump',
      '[Dd]esktop.ini',
      '$RECYCLE.BIN/',
      '*.cab',
      '*.msi',
      '*.msix',
      '*.msm',
      '*.msp',
      '*.lnk',
    ],
  },
  {
    id: 'linux',
    label: 'Linux',
    patterns: [
      '# Linux',
      '*~',
      '.fuse_hidden*',
      '.directory',
      '.Trash-*',
      '.nfs*',
    ],
  },
  {
    id: 'vscode',
    label: 'VS Code',
    patterns: [
      '# VS Code',
      '.vscode/*',
      '!.vscode/settings.json',
      '!.vscode/tasks.json',
      '!.vscode/launch.json',
      '!.vscode/extensions.json',
      '!.vscode/*.code-snippets',
      '.history/',
      '*.vsix',
    ],
  },
  {
    id: 'jetbrains',
    label: 'JetBrains IDEs',
    patterns: [
      '# JetBrains',
      '.idea/',
      '*.iws',
      '*.iml',
      '*.ipr',
      'out/',
      '!**/src/main/**/out/',
      '!**/src/test/**/out/',
      'atlassian-ide-plugin.xml',
      'com_crashlytics_export_strings.xml',
      'crashlytics.properties',
      'crashlytics-build.properties',
      'fabric.properties',
    ],
  },
  {
    id: 'docker',
    label: 'Docker',
    patterns: [
      '# Docker',
      '.docker/',
      'docker-compose.override.yml',
      '*.env',
      '.env',
    ],
  },
  {
    id: 'terraform',
    label: 'Terraform',
    patterns: [
      '# Terraform',
      '.terraform/',
      '*.tfstate',
      '*.tfstate.*',
      'crash.log',
      'crash.*.log',
      '*.tfvars',
      '*.tfvars.json',
      'override.tf',
      'override.tf.json',
      '*_override.tf',
      '*_override.tf.json',
      '.terraformrc',
      'terraform.rc',
    ],
  },
];

export function generateGitignore(selectedIds: string[]): string {
  if (selectedIds.length === 0) return '';

  const seen = new Set<string>();
  const lines: string[] = [
    `# Generated by DevOven Gitignore Generator`,
    `# https://www.devoven.com/tools/gitignore-gen`,
    ``,
  ];

  for (const id of selectedIds) {
    const pt = PROJECT_TYPES.find(p => p.id === id);
    if (!pt) continue;
    for (const line of pt.patterns) {
      if (!seen.has(line)) {
        seen.add(line);
        lines.push(line);
      }
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}
