import { PROJECT_TYPES, generateGitignore } from '@/Components/Functions/GitignoreGenTools/logic';

describe('PROJECT_TYPES', () => {
  it('has at least 15 project types', () => {
    expect(PROJECT_TYPES.length).toBeGreaterThanOrEqual(15);
  });

  it('each project type has id, label, patterns', () => {
    for (const pt of PROJECT_TYPES) {
      expect(pt.id).toBeTruthy();
      expect(pt.label).toBeTruthy();
      expect(Array.isArray(pt.patterns)).toBe(true);
      expect(pt.patterns.length).toBeGreaterThan(0);
    }
  });

  it('contains node, python, go, rust, java, dotnet', () => {
    const ids = PROJECT_TYPES.map(p => p.id);
    expect(ids).toContain('node');
    expect(ids).toContain('python');
    expect(ids).toContain('go');
    expect(ids).toContain('rust');
    expect(ids).toContain('java');
    expect(ids).toContain('dotnet');
  });
});

describe('generateGitignore', () => {
  it('returns empty string for empty selection', () => {
    expect(generateGitignore([])).toBe('');
  });

  it('generates output for node', () => {
    const output = generateGitignore(['node']);
    expect(output).toContain('node_modules/');
    expect(output).toContain('# Node.js');
  });

  it('combines multiple types without duplicates', () => {
    const output = generateGitignore(['node', 'react']);
    expect(output).toContain('node_modules/');
    expect(output).toContain('.next/');
    // node_modules/ should appear only once
    const count = output.split('node_modules/').length - 1;
    expect(count).toBe(1);
  });

  it('includes header comment', () => {
    const output = generateGitignore(['python']);
    expect(output).toContain('Generated by DevOven');
  });

  it('generates python patterns', () => {
    const output = generateGitignore(['python']);
    expect(output).toContain('__pycache__/');
    expect(output).toContain('.pytest_cache/');
  });

  it('generates rust patterns', () => {
    const output = generateGitignore(['rust']);
    expect(output).toContain('/target/');
  });

  it('generates macos patterns', () => {
    const output = generateGitignore(['macos']);
    expect(output).toContain('.DS_Store');
  });
});
